services:
  mongodb:
    image: mongo:latest
    container_name: server_mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: server_mongo_express_container
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://admin:pass@mongodb:27017/
      ME_CONFIG_MONGODB_SERVER: mongodb  # Asegúrate de que este nombre coincide con el nombre del servicio "mongodb"
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance  # Opcional, para cambiar el tema
    ports:
      - "8081:8081"

volumes:
  mongodb_data:
    driver: local